sudo: false
language: scala
jdk:
- openjdk8
script:
- sbt package
deploy:
  provider: releases
  api_key:
    secure: ao3xJ/nChTuqadwa/f6J7ckHtL1aB6+BPjxq+5HmVlARrO3e4wAgvH5daCBSDFmuKMTeH2c1wJ6XyBbIULHHsO6g/geUsSNZZhj06Efw4VeTMwsrp8eY/9rCPXFbtDPKeEviZNt1RX6klTyDGnXyTYQtR0vszVF+a4sLPjNTHerHT2rPrC3oyR3KvTYtFICfpQXjdl3lJPkxuDpeBXF5p7Op7qlyC55ZZVY+MKW/MaF5jwYeor2nwMMKGrito/I35oHdpmZqb6n8Bn/uxAqah1CUfS8K4BdP0XDv98WpC9U5StgaN42CNTCh1i7jNwtNUgw9t63E3b1tzWDdSCpvAV4G8zAlyDEjzTJ0eB1wewwAR6vOFuEjmnDslosMafKoxRZGCRUHwOQhBMFr++B9PdfRTpJy/3hQJyhJYB9iJd7ocoGPzRoodZFoimnmB+CFhy4dJdbJCbeVzXjVSE8D2HMqa0WJRgpt8/Y5ih/HWvVkXSf9CR5vQ9HItk9jil0WsgSBMv/0HwsShtmsffl1lRDmeTmzWW/uXni3tEVWvAehbcz6pcLs5d4rEzJzfj9nEGAthyUHqj5mmwantJQ1xEvs/MyqS+1g/iZy+PG2ka8WUgP8VCz+FpibS6eXejdWOcmhomXlfkpU7lBvNAkLwhpP8iCFR+iyS44R4aIeAw0=
  file_glob: true
  file: "$TRAVIS_BUILD_DIR/target/**/*.jar"
  skip_cleanup: true
  on:
    repo: tohosokawa/gitbucket-branch-protect-plugin
    tags: true
